spring.application.name=Travel

spring.datasource.url=j
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.key=
groq.model=llama-3.3-70b-versatile


spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cache TTL 
ai.cache.ttl=3600